vcpkg install ncnn[vulkan]
vcpkg install wxWidgets[webview]
vcpkg install sdl2
vcpkg install x265
vcpkg install libde265
vcpkg install opencv4[contrib,core,dnn-cuda,dnn,ffmpeg,ipp,jpeg,tbb,png,tiff,webp,openexr,cuda,opengl] --recurse
vcpkg install opencl
vcpkg install dav1d
vcpkg install exiv2[video,xmp,bmff]
vcpkg install libavif[aom,dav1d]
vcpkg install libmediainfo
vcpkg install libexif
vcpkg install jasper
vcpkg install libraw[dng-lossy,openmp]
vcpkg install poppler
vcpkg install sqlite3
vcpkg install freeimage
vcpkg install libjxl
vcpkg install libepoxy
vcpkg install openal-soft
