vcpkg install libde265:x64-windows
vcpkg install sdl2:x64-windows
vcpkg install sqlite3:x64-windows
vcpkg install freeglut:x64-windows
vcpkg install OpenExr:x64-windows
vcpkg install libraw:x64-windows
vcpkg install jasper:x64-windows
vcpkg install exiv2[video,xmp]:x64-windows
vcpkg install wxWidgets[webview]:x64-windows
vcpkg install opencv[contrib,ipp,openmp,opengl,ffmpeg]:x64-windows
vcpkg install freeimage:x64-windows
vcpkg install poppler:x64-windows
vcpkg install libmediainfo:x64-windows
vcpkg install libepoxy:x64-windows
vcpkg install opencl:x64-windows
vcpkg install libexif:x64-windows
vcpkg install libjxl:x64-windows
vcpkg install tbb:x64-windows
vcpkg install libavif:x64-windows
vcpkg install libheif:x64-windows
vcpkg install x265:x64-windows
