//////////////////////////////////////////////////////////////////////////////
// Name:        SVGDocument_CreateElement.cpp
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by genSvgElement.py
//////////////////////////////////////////////////////////////////////////////

#include "wx/wxprec.h"
#ifndef WX_PRECOMP
#include <wx/wx.h>
#endif
#include <wxSVG/SVGAElement.h>
#include <wxSVG/SVGAltGlyphElement.h>
#include <wxSVG/SVGAltGlyphDefElement.h>
#include <wxSVG/SVGAltGlyphItemElement.h>
#include <wxSVG/SVGAnimateElement.h>
#include <wxSVG/SVGAnimateColorElement.h>
#include <wxSVG/SVGAnimateMotionElement.h>
#include <wxSVG/SVGAnimateTransformElement.h>
#include <wxSVG/SVGCircleElement.h>
#include <wxSVG/SVGClipPathElement.h>
#include <wxSVG/SVGColorProfileElement.h>
#include <wxSVG/SVGCursorElement.h>
#include <wxSVG/SVGDefinitionSrcElement.h>
#include <wxSVG/SVGDefsElement.h>
#include <wxSVG/SVGDescElement.h>
#include <wxSVG/SVGEllipseElement.h>
#include <wxSVG/SVGFEBlendElement.h>
#include <wxSVG/SVGFEColorMatrixElement.h>
#include <wxSVG/SVGFEComponentTransferElement.h>
#include <wxSVG/SVGFECompositeElement.h>
#include <wxSVG/SVGFEConvolveMatrixElement.h>
#include <wxSVG/SVGFEDiffuseLightingElement.h>
#include <wxSVG/SVGFEDisplacementMapElement.h>
#include <wxSVG/SVGFEDistantLightElement.h>
#include <wxSVG/SVGFEFloodElement.h>
#include <wxSVG/SVGFEFuncAElement.h>
#include <wxSVG/SVGFEFuncBElement.h>
#include <wxSVG/SVGFEFuncGElement.h>
#include <wxSVG/SVGFEFuncRElement.h>
#include <wxSVG/SVGFEGaussianBlurElement.h>
#include <wxSVG/SVGFEImageElement.h>
#include <wxSVG/SVGFEMergeElement.h>
#include <wxSVG/SVGFEMergeNodeElement.h>
#include <wxSVG/SVGFEMorphologyElement.h>
#include <wxSVG/SVGFEOffsetElement.h>
#include <wxSVG/SVGFEPointLightElement.h>
#include <wxSVG/SVGFESpecularLightingElement.h>
#include <wxSVG/SVGFESpotLightElement.h>
#include <wxSVG/SVGFETileElement.h>
#include <wxSVG/SVGFETurbulenceElement.h>
#include <wxSVG/SVGFilterElement.h>
#include <wxSVG/SVGFontElement.h>
#include <wxSVG/SVGFontFaceElement.h>
#include <wxSVG/SVGFontFaceFormatElement.h>
#include <wxSVG/SVGFontFaceNameElement.h>
#include <wxSVG/SVGFontFaceSrcElement.h>
#include <wxSVG/SVGFontFaceUriElement.h>
#include <wxSVG/SVGForeignObjectElement.h>
#include <wxSVG/SVGGElement.h>
#include <wxSVG/SVGGlyphElement.h>
#include <wxSVG/SVGGlyphRefElement.h>
#include <wxSVG/SVGHKernElement.h>
#include <wxSVG/SVGImageElement.h>
#include <wxSVG/SVGLineElement.h>
#include <wxSVG/SVGLinearGradientElement.h>
#include <wxSVG/SVGMarkerElement.h>
#include <wxSVG/SVGMaskElement.h>
#include <wxSVG/SVGMetadataElement.h>
#include <wxSVG/SVGMissingGlyphElement.h>
#include <wxSVG/SVGMPathElement.h>
#include <wxSVG/SVGPathElement.h>
#include <wxSVG/SVGPatternElement.h>
#include <wxSVG/SVGPolygonElement.h>
#include <wxSVG/SVGPolylineElement.h>
#include <wxSVG/SVGRadialGradientElement.h>
#include <wxSVG/SVGRectElement.h>
#include <wxSVG/SVGScriptElement.h>
#include <wxSVG/SVGSetElement.h>
#include <wxSVG/SVGStopElement.h>
#include <wxSVG/SVGStyleElement.h>
#include <wxSVG/SVGSVGElement.h>
#include <wxSVG/SVGSwitchElement.h>
#include <wxSVG/SVGSymbolElement.h>
#include <wxSVG/SVGTBreakElement.h>
#include <wxSVG/SVGTextElement.h>
#include <wxSVG/SVGTextPathElement.h>
#include <wxSVG/SVGTitleElement.h>
#include <wxSVG/SVGTRefElement.h>
#include <wxSVG/SVGTSpanElement.h>
#include <wxSVG/SVGUseElement.h>
#include <wxSVG/SVGVideoElement.h>
#include <wxSVG/SVGViewElement.h>
#include <wxSVG/SVGVKernElement.h>
#include <wxSVG/SVGElement.h>
#include <wxSVG/SVGDocument.h>

wxSvgXmlElement* wxSVGDocument::CreateElementNS(const wxString& namespaceURI,
  const wxString& qualifiedName)
{
  wxSVGElement* res = NULL;
  if (qualifiedName == wxT("a"))
    res = new wxSVGAElement();
  else if (qualifiedName == wxT("altGlyph"))
    res = new wxSVGAltGlyphElement();
  else if (qualifiedName == wxT("altGlyphDef"))
    res = new wxSVGAltGlyphDefElement();
  else if (qualifiedName == wxT("altGlyphItem"))
    res = new wxSVGAltGlyphItemElement();
  else if (qualifiedName == wxT("animate"))
    res = new wxSVGAnimateElement();
  else if (qualifiedName == wxT("animateColor"))
    res = new wxSVGAnimateColorElement();
  else if (qualifiedName == wxT("animateMotion"))
    res = new wxSVGAnimateMotionElement();
  else if (qualifiedName == wxT("animateTransform"))
    res = new wxSVGAnimateTransformElement();
  else if (qualifiedName == wxT("circle"))
    res = new wxSVGCircleElement();
  else if (qualifiedName == wxT("clipPath"))
    res = new wxSVGClipPathElement();
  else if (qualifiedName == wxT("color-profile"))
    res = new wxSVGColorProfileElement();
  else if (qualifiedName == wxT("cursor"))
    res = new wxSVGCursorElement();
  else if (qualifiedName == wxT("definition-src"))
    res = new wxSVGDefinitionSrcElement();
  else if (qualifiedName == wxT("defs"))
    res = new wxSVGDefsElement();
  else if (qualifiedName == wxT("desc"))
    res = new wxSVGDescElement();
  else if (qualifiedName == wxT("ellipse"))
    res = new wxSVGEllipseElement();
  else if (qualifiedName == wxT("feBlend"))
    res = new wxSVGFEBlendElement();
  else if (qualifiedName == wxT("feColorMatrix"))
    res = new wxSVGFEColorMatrixElement();
  else if (qualifiedName == wxT("feComponentTransfer"))
    res = new wxSVGFEComponentTransferElement();
  else if (qualifiedName == wxT("feComposite"))
    res = new wxSVGFECompositeElement();
  else if (qualifiedName == wxT("feConvolveMatrix"))
    res = new wxSVGFEConvolveMatrixElement();
  else if (qualifiedName == wxT("feDiffuseLighting"))
    res = new wxSVGFEDiffuseLightingElement();
  else if (qualifiedName == wxT("feDisplacementMap"))
    res = new wxSVGFEDisplacementMapElement();
  else if (qualifiedName == wxT("feDistantLight"))
    res = new wxSVGFEDistantLightElement();
  else if (qualifiedName == wxT("feFlood"))
    res = new wxSVGFEFloodElement();
  else if (qualifiedName == wxT("feFuncA"))
    res = new wxSVGFEFuncAElement();
  else if (qualifiedName == wxT("feFuncB"))
    res = new wxSVGFEFuncBElement();
  else if (qualifiedName == wxT("feFuncG"))
    res = new wxSVGFEFuncGElement();
  else if (qualifiedName == wxT("feFuncR"))
    res = new wxSVGFEFuncRElement();
  else if (qualifiedName == wxT("feGaussianBlur"))
    res = new wxSVGFEGaussianBlurElement();
  else if (qualifiedName == wxT("feImage"))
    res = new wxSVGFEImageElement();
  else if (qualifiedName == wxT("feMerge"))
    res = new wxSVGFEMergeElement();
  else if (qualifiedName == wxT("feMergeNode"))
    res = new wxSVGFEMergeNodeElement();
  else if (qualifiedName == wxT("feMorphology"))
    res = new wxSVGFEMorphologyElement();
  else if (qualifiedName == wxT("feOffset"))
    res = new wxSVGFEOffsetElement();
  else if (qualifiedName == wxT("fePointLight"))
    res = new wxSVGFEPointLightElement();
  else if (qualifiedName == wxT("feSpecularLighting"))
    res = new wxSVGFESpecularLightingElement();
  else if (qualifiedName == wxT("feSpotLight"))
    res = new wxSVGFESpotLightElement();
  else if (qualifiedName == wxT("feTile"))
    res = new wxSVGFETileElement();
  else if (qualifiedName == wxT("feTurbulence"))
    res = new wxSVGFETurbulenceElement();
  else if (qualifiedName == wxT("filter"))
    res = new wxSVGFilterElement();
  else if (qualifiedName == wxT("font"))
    res = new wxSVGFontElement();
  else if (qualifiedName == wxT("font-face"))
    res = new wxSVGFontFaceElement();
  else if (qualifiedName == wxT("font-face-format"))
    res = new wxSVGFontFaceFormatElement();
  else if (qualifiedName == wxT("font-face-name"))
    res = new wxSVGFontFaceNameElement();
  else if (qualifiedName == wxT("font-face-src"))
    res = new wxSVGFontFaceSrcElement();
  else if (qualifiedName == wxT("font-face-uri"))
    res = new wxSVGFontFaceUriElement();
  else if (qualifiedName == wxT("foreignObject"))
    res = new wxSVGForeignObjectElement();
  else if (qualifiedName == wxT("g"))
    res = new wxSVGGElement();
  else if (qualifiedName == wxT("glyph"))
    res = new wxSVGGlyphElement();
  else if (qualifiedName == wxT("glyphRef"))
    res = new wxSVGGlyphRefElement();
  else if (qualifiedName == wxT("hkern"))
    res = new wxSVGHKernElement();
  else if (qualifiedName == wxT("image"))
    res = new wxSVGImageElement();
  else if (qualifiedName == wxT("line"))
    res = new wxSVGLineElement();
  else if (qualifiedName == wxT("linearGradient"))
    res = new wxSVGLinearGradientElement();
  else if (qualifiedName == wxT("marker"))
    res = new wxSVGMarkerElement();
  else if (qualifiedName == wxT("mask"))
    res = new wxSVGMaskElement();
  else if (qualifiedName == wxT("metadata"))
    res = new wxSVGMetadataElement();
  else if (qualifiedName == wxT("missing-glyph"))
    res = new wxSVGMissingGlyphElement();
  else if (qualifiedName == wxT("mpath"))
    res = new wxSVGMPathElement();
  else if (qualifiedName == wxT("path"))
    res = new wxSVGPathElement();
  else if (qualifiedName == wxT("pattern"))
    res = new wxSVGPatternElement();
  else if (qualifiedName == wxT("polygon"))
    res = new wxSVGPolygonElement();
  else if (qualifiedName == wxT("polyline"))
    res = new wxSVGPolylineElement();
  else if (qualifiedName == wxT("radialGradient"))
    res = new wxSVGRadialGradientElement();
  else if (qualifiedName == wxT("rect"))
    res = new wxSVGRectElement();
  else if (qualifiedName == wxT("script"))
    res = new wxSVGScriptElement();
  else if (qualifiedName == wxT("set"))
    res = new wxSVGSetElement();
  else if (qualifiedName == wxT("stop"))
    res = new wxSVGStopElement();
  else if (qualifiedName == wxT("style"))
    res = new wxSVGStyleElement();
  else if (qualifiedName == wxT("svg"))
    res = new wxSVGSVGElement();
  else if (qualifiedName == wxT("switch"))
    res = new wxSVGSwitchElement();
  else if (qualifiedName == wxT("symbol"))
    res = new wxSVGSymbolElement();
  else if (qualifiedName == wxT("tbreak"))
    res = new wxSVGTBreakElement();
  else if (qualifiedName == wxT("text"))
    res = new wxSVGTextElement();
  else if (qualifiedName == wxT("textPath"))
    res = new wxSVGTextPathElement();
  else if (qualifiedName == wxT("title"))
    res = new wxSVGTitleElement();
  else if (qualifiedName == wxT("tref"))
    res = new wxSVGTRefElement();
  else if (qualifiedName == wxT("tspan"))
    res = new wxSVGTSpanElement();
  else if (qualifiedName == wxT("use"))
    res = new wxSVGUseElement();
  else if (qualifiedName == wxT("video"))
    res = new wxSVGVideoElement();
  else if (qualifiedName == wxT("view"))
    res = new wxSVGViewElement();
  else if (qualifiedName == wxT("vkern"))
    res = new wxSVGVKernElement();
  else 
	res = new wxSVGGElement();
  return res;
}
