git checkout RegardsViewer_linux/Package/debian/RegardsViewer/DEBIAN/control
git checkout RegardsViewer_linux/Package/debian/RegardsViewer/usr/share/applications/RegardsViewer.desktop
git checkout RegardsViewer_linux/Package/debian/RegardsViewer/usr/share/doc/RegardsViewer/copyright
git checkout RegardsViewer_linux/RegardsViewer_linux.project
git checkout compilation_linux.sh
git checkout libOpenCLEngine/OpenCLContext.cpp
git checkout libPicture/ImageLoadingFormat.cpp
git checkout libWindow/Icone.cpp
git checkout libextern/compilation_library_linux.sh
git checkout libextern/heif-master.zip
git checkout RegardsViewer_linux/Package/snap/snapcraft.yaml
git checkout libextern/vcpkg-master_wayland.tar.gz
git checkout libPicture/libPicture.cpp