.PHONY: clean All

All:
	@echo "----------Building project:[ wxSVG - Debug ]----------"
	@cd "wxSVG" && $(MAKE) -f  "wxSVG.mk"
clean:
	@echo "----------Cleaning project:[ wxSVG - Debug ]----------"
	@cd "wxSVG" && $(MAKE) -f  "wxSVG.mk" clean
