.PHONY: clean All

All:
	@echo "----------Building project:[ RegardsRaw - Debug ]----------"
	@cd "RegardsRaw" && "$(MAKE)" -f  "RegardsRaw.mk"
clean:
	@echo "----------Cleaning project:[ RegardsRaw - Debug ]----------"
	@cd "RegardsRaw" && "$(MAKE)" -f  "RegardsRaw.mk" clean
