name: regardsviewer
title: RegardsViewer 3.0
contact: appt.jf@outlook.fr
donation: https://fr.tipeee.com/regardsviewer
website: https://regardsviewerlite.tiiny.site

base: core24
version: '3.00.0.0'

summary: Regards is a modern photo viewer.
description: |
  Regards is a modern photo viewer with high-DPI screen support.
  It supports reading and writing picture formats.

grade: stable
confinement: strict
license: GPL-3.0
compression: lzo

plugs:
  desktop:
    mount-host-font-cache: true

  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes

  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes

  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

  gnome-46-2404:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-46-2404

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/webkit2gtk-4.1:
    bind: $SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/webkit2gtk-4.1

  /usr/share/xml/iso-codes:
    bind: $SNAP/gnome-platform/usr/share/xml/iso-codes

  /usr/share/libdrm:
    bind: $SNAP/gnome-platform/usr/share/libdrm

  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri

  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/GL:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/GL

  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libGL.so.1:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libGL.so.1

  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libEGL.so.1:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libEGL.so.1

environment:
  SNAP_DESKTOP_RUNTIME: $SNAP/gnome-platform
  GTK_USE_PORTAL: '1'

  LD_LIBRARY_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri:$SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$LD_LIBRARY_PATH

  LIBGL_DRIVERS_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri:$SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri

  MESA_LOADER_DRIVER_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri:$SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri

  __EGL_VENDOR_LIBRARY_DIRS: $SNAP/usr/share/glvnd/egl_vendor.d:$SNAP/gnome-platform/usr/share/glvnd/egl_vendor.d

  EGL_PLATFORM: x11

  XKB_CONFIG_DATA: $SNAP/usr/share/X11/xkb
  GTK_EXE_PREFIX: $SNAP/usr


parts:
  regardsviewer:
    plugin: dump
    source: RegardsViewer_3.00.0.0-linux-x86_64.tar.gz

    stage-packages:
      # Graphics / OpenGL
      - libdrm2
      - libglu1-mesa
      - libglvnd0
      - libgl1-mesa-dri
      - libvdpau1
      - libxshmfence1

      # OpenCL
      - ocl-icd-libopencl1

      # Multimedia
      - libsdl2-2.0-0
      - libva-drm2
      - libva-glx2
      - libva-wayland2

      # X11
      - libx11-6
      - libxau6
      - libxcb-shape0
      - libxcb-shm0
      - libxcb-xfixes0
      - libxcb1
      - libxdmcp6
      - libxext6
      - libxv1
      - libxcb-dri2-0
      - libxcb-dri3-0
      - libxcb-glx0

      # GTK / WebKit
      - libwebkit2gtk-4.1-0
      - libatk1.0-0
      - libnotify4
      - libepoxy0

      # Network / system
      - libgnutls30
      - libxml2
      - curl
      - libzmq5
      - libsnappy1v5
      - libssh-gcrypt-4
      - libusb-1.0-0

      # Video / V4L
      - libv4l-0
      - libv4l2rds0

      # SANE
      - libsane1

      # Other
      - libslang2
      - libice6
      - libsm6


apps:
  regardsviewer:
    command: usr/bin/RegardsViewer
    desktop: usr/share/applications/RegardsViewer.desktop

    extensions:
      - gnome

    plugs:
      - process-control
      - x11
      - audio-playback
      - hardware-observe
      - opengl
      - alsa
      - mount-observe
      - removable-media
      - dvb
      - pulseaudio
      - wayland
      - network
      - home
      - desktop
      - desktop-legacy
