name: regardsviewer # you probably want to 'snapcraft register <name>'
title: RegardsViewer 2.0
base: core20 # the base snap is the execution environment for this snap
version: '2.72.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Regards is a modern photo viewer. # 79 char long summary
description: Regards is a modern photo viewer with highDPI definition screen Support Picture format reading and writing
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
license: GPL-3.0

plugs:
  graphics-core20:
    interface: content
    target: $SNAP/graphics
    default-provider: mesa-core20
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes:gtk-3-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes:sound-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes:icon-themes
  gnome-3-38-2004:
    interface: content
    target: $SNAP/data-dir/gnome-platform
    default-provider: gnome-3-38-2004:gnome-3-38-2004

layout:
  /etc/fonts:
    bind: $SNAP/etc/fonts
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /var/cache/fontconfig:
    bind: $SNAP_DATA/var/cache/fontconfig
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0
  /usr/lib/dri:
    bind: $SNAP/usr/lib/dri
  /usr/share/X11/xkb:
    bind: $SNAP/usr/share/X11/xkb
  /etc/glvnd:
    bind: $SNAP/etc/glvnd
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri:
    bind: $SNAP/graphics/dri
  /usr/share/glvnd:
    bind: $SNAP/graphics/glvnd
  /usr/share/libdrm:
    bind: $SNAP/graphics/libdrm
  /usr/share/drirc.d:
   bind: $SNAP/graphics/drirc.d

environment:
  LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/graphics/dri:$SNAP/graphics/lib:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/xorg:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
  LIBGL_DRIVERS_PATH: $SNAP/graphics/dri
  __EGL_VENDOR_LIBRARY_DIRS: $SNAP/graphics/glvnd/egl_vendor.d
  EGL_PLATFORM: wayland
  #EGL_LOG_LEVEL: debug
  XKB_CONFIG_DATA: $SNAP/usr/share/X11/xkb
  SNAP_DESKTOP_RUNTIME: $SNAP/data-dir/gnome-platform
  GTK_EXE_PREFIX: $SNAP/usr
  GTK_USE_PORTAL: '1'

parts:
  regardsviewer:
    plugin: dump
    source: https://github.com/jfiguinha/Regards/releases/download/v2.72.1/RegardsViewer_2.72.1-linux-x86_64.tar.gz
    stage-packages:
      - freeglut3
      - libass9
      - libbluray2
      - libbs2b0
      - libcaca0
      - libcdio-paranoia2
      - libchromaprint1
      - libcodec2-0.9
      - libdc1394-22
      - libdrm2
      - libflite1
      - libfribidi0
      - libglu1-mesa
      - libgme0
      - libgnutls30
      - libgsm1
      - libmp3lame0
      - libopenal1
      - libopencore-amrnb0
      - libopencore-amrwb0
      - libopenjp2-7
      - libopenmpt0
      - libopus0
      - libpulse0
      - librsvg2-2
      - librubberband2
      - libsdl2-2.0-0
      - libshine3
      - libslang2
      - libsnappy1v5
      - libsoxr0
      - libspeex1
      - libssh-gcrypt-4
      - libtesseract4
      - libtheora0
      - libtwolame0
      - libusb-1.0-0
      - libv4l-0
      - libv4l2rds0
      - libva-drm2
      - libva-glx2
      - libva-wayland2
      - libvdpau-va-gl1
      - libvo-amrwbenc0
      - libvorbis0a
      - libvorbisenc2
      - libvpx6
      - libwavpack1
      - libwebp6
      - libwebpmux3
      - libx265-179
      - libx11-6
      - libxau6
      - libxcb-shape0
      - libxcb-shm0
      - libxcb-xfixes0
      - libxcb1
      - libxdmcp6
      - libxext6
      - libxml2
      - libxv1
      - libxvidcore4
      - libzmq5
      - libzvbi0
      - mesa-vdpau-drivers
      - ocl-icd-libopencl1
      - mesa-va-drivers
      - libjavascriptcoregtk-4.0-18
      - libgstreamer-plugins-base1.0-0
      - libgstreamer1.0-0
      - libgtk-3-0 
      - libice6
      - libsm6
      - libepoxy0  
      - curl
      - libatk1.0-0  
      - libwebkit2gtk-4.0-37  
      - libfftw3-double3
      - libfftw3-single3    
      - libsane
      - libnotify4
      - fonts-freefont-ttf
      - fonts-arphic-uming
      - fontconfig-config

apps:
  regardsviewer:
    command: usr/bin/RegardsViewer
    desktop: usr/share/applications/RegardsViewer.desktop
    extensions: [gnome-3-38]
    plugs: [x11, audio-playback, jack1, opengl, alsa, mount-observe, removable-media, dvb, avahi-control, unity7, gsettings, pulseaudio, wayland, network, network-bind, home, desktop, desktop-legacy]
