image: ubuntu:16.04
before_script:
  - apt-get update -qq && apt-get install -y -qq autoconf automake build-essential cmake libtool libjpeg8-dev libjbig-dev liblzma-dev ninja-build zlib1g-dev zip wget

stages:
  - build

autoconf:
  stage: build
  script:
    - sh build/gitlab-ci autoconf

cmake-makefiles:
  stage: build
  script:
    - sh build/gitlab-ci cmake "Unix Makefiles" Release

cmake-ninja:
  stage: build
  script:
    - sh build/gitlab-ci cmake "Ninja" Debug
