language: c
compiler:
  - gcc
  - clang

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libpulse-dev portaudio19-dev libsonic-dev

script:
  - ./autogen.sh
  - ./configure
  - make
  - make check
